### ISSUE TITLE
Initialize error on server start

### ISSUE THREAD

**Issue by b4thestorm** [ryanckulp/pushup_metrics#1]
I am looking to run my rails server but I am missing an API key. It looks like the problem is occurring in peanus.rb where there is a call to initialize a new slack::notifier object passing in an env key for slack web hook .  Here is the stack trace:

<img width="1107" alt="screen shot 2016-06-02 at 10 47 03 am" src="https://cloud.githubusercontent.com/assets/4723872/15749139/64bb5638-28af-11e6-9bdb-1aa3dca8d58e.png">

When I go to slack incoming web hooks to request an api key, I am told that i need to choose a channel to get a key for. Any ideas, how to solve this problem??

**Comment by ryanckulp** [comment]
Ah, Slack Notifier is a gem that makes it easy to ping a slack channel. It's try to parse a webhook URL that doesn't exist.

Safe to remove all mentions of the ```Peanus.ping``` call, feel free to submit a PR.
